### ISSUE TITLE
Delegate positions within the project

### ISSUE THREAD

**Issue by vwashington** [team-cs4300/team-project#2]
Separate the parts of the project to each user.

**Comment by vwashington** [comment]
I need one person to take each of these. Please comment on the one you will take.
Abstract and Introduction
~~HTML and CSS design.~~
~~Javascript design~~
Hosting and Deployment / Conclusion

**Comment by kd-Ewe** [comment]
I can work on HTML and CSS design

**Comment by KevinHa59** [comment]
I am not good with JavaScript and also Hosting & Deployment because web development is not my favorite. However, I am quite good with Java, I guess I can read and understand JavaScript, so I will handle JavaScript part.

**Comment by vwashington** [comment]
> I am not good with JavaScript and also Hosting & Deployment because web development is not my favorite. However, I am quite good with Java, I guess I can read and understand JavaScript, so I will handle JavaScript part.

Kevin, if you need help understanding the code let me know. I can help with that.

**Comment by KevinHa59** [comment]
> > I am not good with JavaScript and also Hosting & Deployment because web development is not my favorite. However, I am quite good with Java, I guess I can read and understand JavaScript, so I will handle JavaScript part.
> 
> Kevin, if you need help understanding the code let me know. I can help with that.

Sure.

**Comment by vwashington** [comment]
Looks like I miss read the instructions yesterday, I have added the Intro and Abstract for someone to take.

**Comment by KevinHa59** [comment]
So what we are going to to now is complete our own part on report document, is it right?

**Comment by vwashington** [comment]
Yes, you need to start on the document of your part.
There are two parts left that need to be taken. I can assign them or one of you can pick.
M1 and M4 are left over.

**Comment by KevinHa59** [comment]
How about other members?  Our team has 5 members.

**Comment by vwashington** [comment]
@Uriel-Torres take M4 and @tesselock take M1 please

**Comment by Uriel-Torres** [comment]
Gotcha I'll Take M4

**Comment by trisavo** [comment]
i cant do the abstract until we're done with the whole project because i dont know what the completed project is going to look like.. 
https://docs.google.com/document/d/185cvoMJYSHA2sqEAPVCSP4MB8f9NJ3-DeQK5wK1ME_E/edit?usp=sharing

I started writing on it, feel free to begin writing your parts too

**Comment by KevinHa59** [comment]
@tesselock the project is completed. Pull it from git repo to your PC and run it. What we are going to do now is just finishing report document.

**Comment by trisavo** [comment]
it’s literally just a script file ? i put in houston, tx and nothing showed up. 

i thought it’s already deployed so i just went on the github pages site

Trisa Vo

**Comment by KevinHa59** [comment]
@tesselock you have to download whole project, not just html file. The javascript file makes it work. It works on mine. Moreover, just put the city name only, not state.

**Comment by vwashington** [comment]
Site is now working, we just need to execute my pull request.
All task have been assigned. Project due Dec. 6th.
